version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xajtfbyubyp7"
s3_prefix = "serverless-crud"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
